apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - orders-config.yaml
  - orders-deployment.yaml
  - payments-config.yaml
  - payments-deployment.yaml
  - billing-config.yaml
  - billing-deployment.yaml
