metadata:
  name: "orders"
  namespace: "dev"
  labels:
    app: "orders"
    app.kubernetes.io/part-of: "multi-service-demo"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "orders"
        app.kubernetes.io/part-of: "multi-service-demo"
    spec:
      volumes:
      - configMap:
          name: "orders-page"
        name: "page"
      containers:
      - image: "docker.io/library/nginx:1.27-alpine"
        livenessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: "http"
        name: "nginx"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 2
          httpGet:
            path: "/"
            port: "http"
        ports:
        - name: "http"
          containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html/index.html"
          name: "page"
          readOnly: true
          subPath: "index.html"
  selector:
    matchLabels:
      app: "orders"
  replicas: 1
